# Generated by Django 3.0.3 on 2020-06-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ten_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=264, unique=True)),
            ],
        ),
    ]
